"""change in relation

Revision ID: 0f8ecb010edb
Revises: 623d6b40c853
Create Date: 2018-12-28 13:30:16.857745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f8ecb010edb'
down_revision = '623d6b40c853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
